version: "2"

services:
  api:
    # Existing image in repository
    # image: kthse/docker pull kthse/kth-nodejs-api:13.37

    # Build from Dockerfile in current directory
    build: .

    env_file:
      - ./.env

    # Port published from inside the Docker image
    ports:
      - 3001:3001
