pr: none
trigger:
  branches:
    include:
    - main

variables:
- group: elarande-general-params
- group: elarande-spoke1-ref
- name: appName
  value: lms-web-ref
- name: parametersFileName
  value: lms-web.ref.parameters.json
- name: imageRepository
  value: lms-web
- name: dockerfilePath
  value: '$(Pipeline.Workspace)/github/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: image
  value: '$(imageRepository):$(tag)'
- name: isApi
  value: false


resources:
  repositories:
  - repository: cet-iac
    endpoint: Cet-Iac
    type: git
    name: 'Cloud Excellence Team/cet-iac'
    ref: main
    

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build and push to ref

  jobs:
  - template: templates/deploy-docker-image.yml@cet-iac