trigger: none
pr: none

variables:
- group: elarande-general-params
- group: elarande-spoke1-prod
- name: appName
  value: lms-web-prod
- name: parametersFileName
  value: lms-web.prod.parameters.json
- name: imageRepository
  value: lms-web
- name: isApi
  value: false


resources:
  repositories:
   - repository: cet-iac
     type: git
     name: Cloud Excellence Team/cet-iac

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build and push production

  jobs:
  - template: templates/deploy-docker-image-prod.yml@cet-iac