trigger: none
pr: none

parameters:
  - name: imageTag
    type: string
    displayName: New image tag in production

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-prod

  # Resource name in Azure
  - name: appName
    value: lms-web-prod

  # Docker image name
  - name: imageName
    value: lms-web

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/app-service/update-image.yml@cet-iac
    parameters:
      appName: $(appName)
      imageName: $(imageName)
      tag: ${{ parameters.imageTag }}
      isApi: false
