pr: none
trigger:
  branches:
    include:
      - master

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-ref
  - name: dockerfilePath
    value: "$(Pipeline.Workspace)/github/Dockerfile"
  - name: appName
    value: lms-web-ref
  - name: imageName
    value: lms-web
  - name: tag
    value: "${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:4}"

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/docker/build.yml@cet-iac
    parameters:
      runScan: true
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)
  - template: templates/test/npm-test.yml@cet-iac
  - template: templates/docker/push.yml@cet-iac
    parameters:
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)
  - template: templates/app-service/update-image.yml@cet-iac
    parameters:
      appName: $(appName)
      imageName: $(imageName)
      tag: $(tag)
      isApi: false
