module.exports = [
  {
    id: 3,
    sis_course_id: "ExampleHT18",
    account_id: 14,
    workflow_state: "available",
    course_code: "H",
    is_public: true,
    name: "Example course I HT18",
  },
  {
    id: 3,
    sis_course_id: "ExampleVT18",
    account_id: 14,
    workflow_state: "available",
    course_code: "B",
    is_public: true,
    name: "Example course II VT18",
  },
  {
    id: 3,
    sis_course_id: "ExampleHT18",
    account_id: 24,
    workflow_state: "available",
    course_code: "G",
    is_public: true,
    name: "Example course III HT18",
  },
  {
    id: 3,
    sis_course_id: "ExampleHT16",
    account_id: 24,
    workflow_state: "available",
    course_code: "E",
    is_public: true,
    name: "Example course IV HT16",
  },
  {
    id: 3,
    sis_course_id: "Blablablabl",
    account_id: 67,
    workflow_state: "available",
    course_code: "C",
    is_public: true,
    name: "Example course nowhere",
  },
  {
    id: 3,
    sis_course_id: "ExampleVT17",
    account_id: 27,
    workflow_state: "available",
    course_code: "D",
    is_public: true,
    name: "Example course V VT17",
  },
  {
    id: 3,
    sis_course_id: "ExampleHT17",
    account_id: 29,
    workflow_state: "available",
    course_code: "F",
    is_public: true,
    name: "Example course VI HT18",
  },
  {
    id: 3,
    sis_course_id: "ExampleHT18",
    account_id: 63,
    workflow_state: "available",
    course_code: "A",
    is_public: true,
    name: "Example course VII HT18",
  },
  {
    id: 3,
    sis_course_id: "ExampleHT18",
    account_id: 67,
    workflow_state: "available",
    course_code: "C",
    is_public: true,
    name: "Example course VIII HT18",
  },
  {
    id: 3,
    sis_course_id: "ExampleHT19",
    account_id: 24,
    workflow_state: "available",
    course_code: "C",
    is_public: true,
    name: "Example course XI HT19",
  },
  {
    id: 3,
    sis_course_id: "ExampleVT20",
    account_id: 27,
    workflow_state: "available",
    course_code: "C",
    is_public: true,
    name: "Example course XII VT20",
  },
  {
    id: 3,
    sis_course_id: "ExampleHT20",
    account_id: 29,
    workflow_state: "available",
    course_code: "C",
    is_public: true,
    name: "Example course XIII HT20",
  },
  {
    id: 3,
    sis_course_id: "ExampleVT21",
    account_id: 14,
    workflow_state: "available",
    course_code: "C",
    is_public: true,
    name: "Example course XIV VT21",
  },
];
